### ISSUE TITLE
with source code

### ISSUE THREAD

**Issue by lecheel** [cj-mills/Unity-OpenVINO-YOLOX#1]
thanks the great project will plan release the source code?

**Comment by cj-mills** [comment]
Hi @lecheel , I am currently in the process of writing a tutorial series for this project and will update this repository with the final source code once I have finished. Hopefully, that should be within a week or so.

**Comment by cj-mills** [comment]
Hey @lecheel,
I am still cleaning up the code and finishing the tutorial. However, the current code is available in the [testing branch](https://github.com/cj-mills/Unity-OpenVINO-YOLOX/tree/testing), if you want to check it out now.

The DLL project requires OpenVINO 2021.3.394 to be installed.

When building the Unity project, you will need to add the [models](https://github.com/cj-mills/Unity-OpenVINO-YOLOX/tree/testing#download-models) folder to the build directory and you will need to copy the `OpenVINO_YOLOX_Testing/Plugins/` folder to the `<build_folder>/OpenVINO_YOLOX_Testing_Data/` directory. 

If you are using an Intel integrated GPU or Xe discrete GPU, it may take several seconds the first time OpenVINO uploads a model to the device. Cache files are automatically generated to prevent this the second time a model is used on that device, with a given input resolution.

Full instructions will be provided in the tutorial, but the process is basically the same as for [this project](https://github.com/cj-mills/Unity-OpenVINO-Plugin).
